name: Create Branch Workflow

on:
  workflow_run:
    workflows: ["Manual Trigger"]
    types:
      - completed

jobs:
  create-branch-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Create and Push Branch
      run: |
        # Set the new branch name (customize as needed)
        NEW_BRANCH_NAME=new-branch
        
        # Create a new branch
        git checkout -b $NEW_BRANCH_NAME
        
        # Make changes or perform other actions if needed
        
        # Push the new branch to the repository
        git push origin $NEW_BRANCH_NAME
