name: Create A new Branch

on:
  workflow_dispatch:
    inputs:
      BranchName:
        description: Name of the New branch
        type: string
        required: true
      isPremium:
        description: "Adds premium features to the build"
        type: boolean
        required: false
      preferredTheme:
        description: "Frontend theme"
        type: choice
        default: "light"
        options:
          - "dark"
          - "light"
          - "high-contrast"
    
jobs:
  Create-Branch:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Building for ${{ github.event.inputs.customerName }}"
          echo "Premium customer: ${{ github.event.inputs.isPremium }}"
          echo "Selected theme: ${{ github.event.inputs.preferredTheme }}"


          