name: Create Branch, Tag Release, and Raise Pull Request

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Name of the new branch'
        required: true

jobs:
  create-branch-tag-and-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        
    - name: Create and Push Branch
      run: |
        # Get the new branch name from the workflow input
        NEW_BRANCH_NAME="${{ github.event.inputs.branchName }}"
        
        # Create a new branch based on the main branch
        git checkout -b $NEW_BRANCH_NAME
        
        # Make changes or perform other actions if needed
        
        # Push the new branch to the repository
        git push origin $NEW_BRANCH_NAME

    - name: Get Version from Code
      id: version
      run: |
        # Extract version from your code (replace this with the actual command)
        VERSION=$(cat version.txt)
        echo "Version: $VERSION"
        echo "::set-output name=version::$VERSION"
    
    - name: Create Tag and Push
      run: |
        # Get the version from the previous step
        VERSION="${{ steps.version.outputs.version }}"
        
        # Create a tag based on the version
        git tag -a "v$VERSION" -m "Version $VERSION"
        
        # Push the tag to the repository
        git push origin "v$VERSION"

    - name: Create Pull Request
      run: |
        gh pr create --base main --head ${{ github.event.inputs.branchName }} --title "Create branch: ${{ github.event.inputs.branchName }}" --body "This pull request was automatically created by GitHub Actions."
